name: Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Apply default label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            frontend

      - name: Label based on target branch (develop → feature)
        if: github.base_ref == 'develop'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: feature

      - name: Label based on target branch (master → release)
        if: github.base_ref == 'master'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: release
